export * from "./initTemplate";
export * from "./changeColor";
export * from "./route";
export * from "./axios";
export * from "./dataPokemon";
export * from "./filterDataPokemon";
export * from "./typePokemon";
export * from "./numeroRandom";
export * from "./Hangman/index";
